# Generated by Django 3.0.6 on 2020-05-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedate',
            field=models.DateField(),
        ),
    ]
