# Generated by Django 3.0.6 on 2020-05-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20200517_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='start_date',
            field=models.DateField(),
        ),
    ]
