# Generated by Django 3.0.6 on 2020-05-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20200517_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
