# Generated by Django 3.0.6 on 2020-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20200519_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='start_date',
            field=models.DateField(),
        ),
    ]
