# Generated by Django 3.0.6 on 2020-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20200520_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='status',
            field=models.IntegerField(choices=[(0, 'Upcoming'), (1, 'Completed')], default=0),
            preserve_default=False,
        ),
    ]
