# Generated by Django 3.0.6 on 2020-05-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_upcoming_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='status',
            field=models.IntegerField(choices=[(0, 'Upcoming'), (1, 'Completed')], default=0),
        ),
    ]
