# Generated by Django 3.0.6 on 2020-05-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_auto_20200521_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
